//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class alumnos
{
    public alumnos()
    {
        this.notas = new HashSet<notas>();
    }

    public int alumnoId { get; set; }
    public string alumnoPrimerNombre { get; set; }
    public string alumnoPrimerApellido { get; set; }

    public virtual ICollection<notas> notas { get; set; }
}
