//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class notas
{
    public int notaId { get; set; }
    public Nullable<int> alumnoid { get; set; }
    public Nullable<int> materiaId { get; set; }
    public string notaNota { get; set; }

    public virtual alumnos alumnos { get; set; }
    public virtual materias materias { get; set; }
}
